### ISSUE TITLE
Can't save image on Safari/MacOS 13

### ISSUE THREAD

**Issue by tevendale** [alexandsr/StravaStatsCard#2]
Right/Ctrl-clicking on the generated image doesn't present an option to save the image. I'd expect to see 'Save Image to Downloads' and similar options that I'd see when clicking on a jpg/png file.

<img width="219" alt="Screenshot 2023-08-08 at 18 27 35" src="https://github.com/alexandsr/StravaStatsCard/assets/273540/fc1656aa-5e9d-48c7-bdfb-25ef9a2030e8">

I've also tested this with Chrome on MacOS 13 and it is possible to save the image in that.

**Comment by a0ax** [comment]
lot of CORS issues related to canvas elements so this isn't something i can fix very easily
